server:
  port: 10010                    #zuul网关的端口
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3307/leyou
    username: root
    password: lifulai002100
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka: #把zuul注到eureka中
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka
    registryFetchIntervalSeconds: 10
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1
    instanceId: ${spring.application.name}:${server.port}
     #配置zuul路由
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 访问路径/item/时路由到item-service这个微服务
    search-service: /search/**
    user-service: /user/**
    sms-service: /sms/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**
      serviceId: upload-service   #路径被路由到upload-service服务中
      strip-prefix: false
  host:
      socket-timeout-millis: 100000
      connect-timeout-millis: 100000
  add-host-header: true #携带请求本身的host头信息
  sensitive-headers: #禁止使用头的信息，设置为null，否则set-cookie无效
ribbon:
  ConnectTimeout: 500   # 连接超时时间(ms)
  ReadTimeout: 3000     # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：5000ms
ly:
  #jwt:
    #pubKeyPath: D:\BaiduNetdiskDownload\xx\app\rsa.pub # 公钥地址
    #cookieName: LY_TOKEN
  filter:
    allowPaths:
      #- /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item/ #临时放行，因为需要用登录
      - /zuul/api/upload